<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://practice.learning.com/osb/serviceorchestration/schema/orchestrated"
            targetNamespace="http://practice.learning.com/osb/serviceorchestration/schema/orchestrated"
            elementFormDefault="qualified">

    <xsd:element name="OrchestratedResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="customerId"   type="xsd:string"/>
                <xsd:element name="customerName" type="xsd:string"/>
                <xsd:element name="email"        type="xsd:string"/>
                <xsd:element name="orderId"      type="xsd:string"/>
                <xsd:element name="product"      type="xsd:string"/>
                <xsd:element name="amount"       type="xsd:decimal"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
