<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://practice.learning.com/osb/parallelInvocation/wsdl/customerProfile"
             xmlns:cust="http://practice.learning.com/osb/parallelInvocation/schema/customer"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://practice.learning.com/osb/parallelInvocation/wsdl/customerProfile"
             name="CustomerProfileService">

    <types>
        <xsd:schema>
            <xsd:import namespace="http://practice.learning.com/osb/parallelInvocation/schema/customer"
                        schemaLocation="../Schemas/CustomerRequest.xsd"/>
            <xsd:import namespace="http://practice.learning.com/osb/parallelInvocation/schema/customer"
                        schemaLocation="../Schemas/CustomerProfileResponse.xsd"/>
        </xsd:schema>
    </types>

    <message name="CustomerProfileRequest">
        <part name="parameters" element="cust:CustomerRequest"/>
    </message>
    <message name="CustomerProfileResponseMsg">
        <part name="parameters" element="cust:CustomerProfileResponse"/>
    </message>

    <portType name="CustomerProfilePortType">
        <operation name="getCustomerProfile">
            <input  message="tns:CustomerProfileRequest"/>
            <output message="tns:CustomerProfileResponseMsg"/>
        </operation>
    </portType>

    <binding name="CustomerProfileBinding"
             type="tns:CustomerProfilePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getCustomerProfile">
            <soap:operation soapAction="getCustomerProfile"/>
            <input>  <soap:body use="literal"/> </input>
            <output> <soap:body use="literal"/> </output>
        </operation>
    </binding>

    <service name="CustomerProfileService">
        <port name="CustomerProfilePort"
              binding="tns:CustomerProfileBinding">
            <soap:address location="http://localhost:8011/CustomerProfileService"/>
        </port>
    </service>

</definitions>